name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push API Gateway
        uses: docker/build-push-action@v3
        with:
          context: ./api-gateway
          push: true
          tags: yuri8822/api-gateway:latest
      - name: Build and push Menu Service
        uses: docker/build-push-action@v3
        with:
          context: ./menu-service
          push: true
          tags: yuri8822/menu-service:latest
      - name: Build and push Order Service
        uses: docker/build-push-action@v3
        with:
          context: ./order-service
          push: true
          tags: yuri8822/order-service:latest
      - name: Build and push Inventory Service
        uses: docker/build-push-action@v3
        with:
          context: ./inventory-service
          push: true
          tags: yuri8822/inventory-service:latest
      - name: Build and push Customer Service
        uses: docker/build-push-action@v3
        with:
          context: ./customer-service
          push: true
          tags: yuri8822/customer-service:latest
      - name: Build and push Payment Service
        uses: docker/build-push-action@v3
        with:
          context: ./payment-service
          push: true
          tags: yuri8822/payment-service:latest